name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run validation suite
        run: |
          # Build graph and generate reading lists
          python hub/tools/build_graph.py
          python hub/tools/gen_reading_list.py sample_service implement_api || true

          # Validate without strict mode (allows documentation warnings)
          python hub/tools/validate_context.py

      - name: Check for uncommitted changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Error: Scripts generated uncommitted changes"
            git status
            exit 1
          fi
